[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc"]

[phases.install]
cmds = ["pip3 install -r requirements.txt --break-system-packages"]

[start]
cmd = "python3 -m gunicorn insighta_labs.wsgi --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
